export function DisclaimerFooter() {
  return (
    <footer style={{
      marginTop: "64px",
      borderTop: "1px solid var(--border)",
      padding: "24px 24px 32px",
      background: "var(--bg)",
    }}>
      <div className="max-w-7xl mx-auto">
        <p className="text-xs leading-relaxed" style={{ color: "#3a3a3a" }}>
          DeepPuts provides AI-generated market analysis for research and educational purposes only.
          Nothing on this platform constitutes investment advice, a solicitation to trade, or a recommendation
          to buy or sell any security or derivative. Conviction scores are experimental metrics and do not
          predict returns or price movements. Short selling and options trading carry significant risk,
          including the potential loss of more than your initial investment. Market data provided by{" "}
          <span style={{ color: "#4a4a4a" }}>Polygon.io</span>. AI analysis generated by{" "}
          <span style={{ color: "#4a4a4a" }}>Anthropic Claude</span>. Past signal performance does not
          indicate future results. DeepPuts is not a registered investment advisor, broker-dealer, or
          financial institution. Always conduct independent due diligence before making any investment
          decision. Use at your own risk.
        </p>
        <p className="text-xs mt-3" style={{ color: "#2a2a2a" }}>
          © {new Date().getFullYear()} DeepPuts
        </p>
      </div>
    </footer>
  );
}
