import Link from "next/link";
import { TrendingDown } from "lucide-react";

export const metadata = { title: "Terms of Service — DeepPuts" };

export default function TermsOfService() {
  return (
    <div className="min-h-screen" style={{ background: "var(--bg)" }}>
      <header className="border-b" style={{ borderColor: "var(--border)", background: "rgba(8,8,8,0.9)" }}>
        <div className="max-w-3xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <TrendingDown size={16} style={{ color: "#f43f5e" }} />
            <span className="text-sm font-bold tracking-tight text-white">
              Deep<span style={{ color: "#f43f5e" }}>Puts</span>
            </span>
          </Link>
          <Link href="/" className="text-xs transition-colors" style={{ color: "var(--text-3)" }}
            onMouseEnter={undefined}
          >← Back</Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-10">
          <h1 className="text-3xl font-bold tracking-tight mb-2" style={{ color: "var(--text)" }}>Terms of Service</h1>
          <p className="text-sm" style={{ color: "var(--text-3)" }}>Last updated: June 2026</p>
        </div>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: "var(--text-2)" }}>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>1. Acceptance of Terms</h2>
            <p>By accessing or using DeepPuts (&ldquo;the Platform&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Platform. DeepPuts reserves the right to modify these terms at any time; continued use constitutes acceptance of any changes.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>2. Not Financial Advice</h2>
            <p className="mb-3">
              <strong style={{ color: "var(--text)" }}>DeepPuts is not a financial advisor, broker-dealer, investment advisor, or securities dealer.</strong> All content on the Platform — including AI-generated bear theses, conviction scores, signal classifications, price performance data, and community discussions — is provided for <strong style={{ color: "var(--text)" }}>informational and educational purposes only</strong>.
            </p>
            <p className="mb-3">Nothing on the Platform constitutes:</p>
            <ul className="space-y-1.5 ml-4">
              {[
                "Investment advice or a recommendation to buy, sell, or hold any security or asset",
                "An offer or solicitation to purchase or sell any financial instrument",
                "A guarantee of future returns or performance",
                "Tax, legal, or accounting advice",
              ].map((item, i) => (
                <li key={i} className="flex gap-2"><span style={{ color: "#444" }}>•</span>{item}</li>
              ))}
            </ul>
            <p className="mt-3">
              <strong style={{ color: "var(--text)" }}>Short selling and options trading carry significant risk of loss</strong>, including the possibility of losses exceeding your initial investment. Always consult a licensed financial professional before making any investment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>3. AI-Generated Content</h2>
            <p className="mb-3">
              Analysis on the Platform is generated by artificial intelligence models (currently Anthropic Claude) and is <strong style={{ color: "var(--text)" }}>automatically produced without human review</strong>. AI-generated content:
            </p>
            <ul className="space-y-1.5 ml-4 mb-3">
              {[
                "May be inaccurate, incomplete, or misleading",
                "Does not reflect the views or opinions of DeepPuts or its operators",
                "Should not be relied upon as the sole basis for any investment decision",
                "May contain errors in ticker identification, sector classification, or thesis construction",
              ].map((item, i) => (
                <li key={i} className="flex gap-2"><span style={{ color: "#444" }}>•</span>{item}</li>
              ))}
            </ul>
            <p>DeepPuts makes no warranty regarding the accuracy, timeliness, or completeness of any AI-generated analysis.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>4. User Accounts</h2>
            <p>You are responsible for maintaining the confidentiality of your account credentials. You agree not to use the Platform to post misleading, manipulative, or false information about securities. DeepPuts reserves the right to suspend or terminate accounts that violate these terms.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>5. User-Generated Content</h2>
            <p>By posting comments or other content on the Platform, you grant DeepPuts a non-exclusive license to display and distribute that content. You are solely responsible for ensuring your content does not constitute market manipulation, securities fraud, or other illegal activity. DeepPuts is not liable for user-generated content.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>6. Market Data</h2>
            <p>Price and market data displayed on the Platform is sourced from Polygon.io and other third-party providers. Data may be delayed and is provided without guarantee of accuracy. DeepPuts is not responsible for errors or omissions in market data.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>7. Limitation of Liability</h2>
            <p>DeepPuts and its operators shall not be liable for any direct, indirect, incidental, special, or consequential damages arising from your use of the Platform, including financial losses resulting from reliance on any content published on the Platform.</p>
          </section>

          <section>
            <h2 className="text-base font-semibold mb-3" style={{ color: "var(--text)" }}>8. Contact</h2>
            <p>For questions about these terms, contact us at the email address on file. These terms are governed by applicable law.</p>
          </section>

        </div>

        <div className="mt-12 pt-6" style={{ borderTop: "1px solid var(--border)" }}>
          <Link href="/privacy" className="text-xs transition-colors" style={{ color: "var(--text-3)" }}
            onMouseEnter={undefined}
          >Privacy Policy →</Link>
        </div>
      </main>
    </div>
  );
}
