"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { TrendingDown, AlertTriangle, CheckCircle } from "lucide-react";

export function OnboardingModal() {
  const { data: session, status } = useSession();
  const [show, setShow] = useState(false);
  const [accepting, setAccepting] = useState(false);
  const [checked, setChecked] = useState(false);

  useEffect(() => {
    if (status !== "authenticated" || !session?.user?.id) return;
    fetch("/api/user/me")
      .then(r => r.json())
      .then(d => {
        if (!d.acceptedTermsAt) setShow(true);
      })
      .catch(() => {});
  }, [status, session?.user?.id]);

  async function accept() {
    if (!checked) return;
    setAccepting(true);
    await fetch("/api/user/accept-terms", { method: "POST" });
    setShow(false);
    setAccepting(false);
  }

  if (!show) return null;

  return (
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.85)", backdropFilter: "blur(4px)" }}
    >
      <div
        className="w-full max-w-md rounded-2xl p-8 space-y-6"
        style={{ background: "var(--surface)", border: "1px solid rgba(244,63,94,0.2)" }}
      >
        {/* Header */}
        <div className="flex flex-col items-center text-center gap-3">
          <div className="w-12 h-12 rounded-2xl flex items-center justify-center"
            style={{ background: "rgba(244,63,94,0.1)", border: "1px solid rgba(244,63,94,0.2)" }}>
            <TrendingDown size={22} style={{ color: "#f43f5e" }} />
          </div>
          <div>
            <h2 className="text-lg font-semibold tracking-tight" style={{ color: "var(--text)" }}>
              Welcome to DeepPuts
            </h2>
            <p className="text-sm mt-1" style={{ color: "var(--text-3)" }}>
              AI-powered bearish market intelligence
            </p>
          </div>
        </div>

        {/* Risk disclaimer */}
        <div className="rounded-xl p-4 space-y-3"
          style={{ background: "rgba(245,158,11,0.05)", border: "1px solid rgba(245,158,11,0.2)" }}>
          <div className="flex items-center gap-2">
            <AlertTriangle size={14} style={{ color: "#f59e0b", flexShrink: 0 }} />
            <span className="text-xs font-semibold uppercase tracking-wider" style={{ color: "#f59e0b" }}>
              Important Disclosure
            </span>
          </div>
          <ul className="space-y-2 text-xs leading-relaxed" style={{ color: "var(--text-2)" }}>
            <li>• DeepPuts provides <strong style={{ color: "var(--text)" }}>AI-generated analysis for research and educational purposes only</strong> — not investment advice.</li>
            <li>• All bear theses, conviction scores, and signal classifications are <strong style={{ color: "var(--text)" }}>automatically generated by AI</strong> and may be inaccurate, incomplete, or misleading.</li>
            <li>• Short selling and put options strategies carry <strong style={{ color: "var(--text)" }}>significant risk of unlimited losses</strong>. You can lose more than your initial investment.</li>
            <li>• Past performance of flagged signals is <strong style={{ color: "var(--text)" }}>not indicative of future results</strong>.</li>
            <li>• Always conduct your own due diligence and consult a licensed financial advisor before making any investment decisions.</li>
          </ul>
        </div>

        {/* What DeepPuts is */}
        <div className="space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--text-3)" }}>What DeepPuts is</p>
          <div className="grid grid-cols-2 gap-2">
            {[
              "Research starting point",
              "Signal aggregator",
              "Community discussion",
              "Performance tracker",
            ].map(item => (
              <div key={item} className="flex items-center gap-2 text-xs" style={{ color: "var(--text-2)" }}>
                <CheckCircle size={11} style={{ color: "#22c55e", flexShrink: 0 }} />
                {item}
              </div>
            ))}
          </div>
        </div>

        {/* Checkbox acceptance */}
        <label className="flex items-start gap-3 cursor-pointer">
          <input
            type="checkbox"
            checked={checked}
            onChange={e => setChecked(e.target.checked)}
            className="mt-0.5 shrink-0 w-4 h-4 rounded"
            style={{ accentColor: "#f43f5e" }}
          />
          <span className="text-xs leading-relaxed" style={{ color: "var(--text-2)" }}>
            I understand that DeepPuts is not financial advice, I accept the{" "}
            <a href="/tos" target="_blank" rel="noopener noreferrer" style={{ color: "#f43f5e" }}>Terms of Service</a>{" "}
            and{" "}
            <a href="/privacy" target="_blank" rel="noopener noreferrer" style={{ color: "#f43f5e" }}>Privacy Policy</a>,
            and I acknowledge the risks involved in bearish trading strategies.
          </span>
        </label>

        <button
          onClick={accept}
          disabled={!checked || accepting}
          className="w-full py-2.5 text-sm font-medium rounded-xl transition-all"
          style={{
            background: !checked || accepting ? "rgba(244,63,94,0.3)" : "#f43f5e",
            color: "#fff",
            cursor: !checked || accepting ? "not-allowed" : "pointer",
          }}
          onMouseEnter={e => { if (checked && !accepting) e.currentTarget.style.background = "#fb4f6b"; }}
          onMouseLeave={e => { if (checked && !accepting) e.currentTarget.style.background = "#f43f5e"; }}
        >
          {accepting ? "Saving…" : "I Understand — Enter DeepPuts"}
        </button>
      </div>
    </div>
  );
}
