"use client";

import { useState, useEffect } from "react";
import { useSession } from "next-auth/react";
import { TrendingDown, AlertTriangle, CheckCircle } from "lucide-react";

export function OnboardingModal() {
  const { data: session, status } = useSession();
  const [show, setShow] = useState(false);
  const [accepting, setAccepting] = useState(false);
  const [checks, setChecks] = useState([false, false, false]);
  
  const allChecked = checks.every(c => c);

  useEffect(() => {
    if (status !== "authenticated" || !session?.user?.id) return;
    fetch("/api/user/me")
      .then(r => r.json())
      .then(d => {
        if (!d.acceptedTermsAt) setShow(true);
      })
      .catch(() => {});
  }, [status, session?.user?.id]);

  async function accept() {
    if (!allChecked) return;
    setAccepting(true);
    await fetch("/api/user/accept-terms", { method: "POST" });
    setShow(false);
    setAccepting(false);
  }

  if (!show) return null;

  return (
    <div
      className="fixed inset-0 z-[200] flex items-center justify-center p-4"
      style={{ background: "rgba(0,0,0,0.85)", backdropFilter: "blur(4px)" }}
    >
      <div
        className="w-full max-w-lg rounded-2xl p-8 space-y-6 shadow-2xl"
        style={{ background: "rgba(12,12,12,0.95)", border: "1px solid rgba(244,63,94,0.3)", backdropFilter: "blur(12px)" }}
      >
        {/* Header */}
        <div className="flex flex-col items-center text-center gap-3">
          <div className="w-12 h-12 rounded-2xl flex items-center justify-center"
            style={{ background: "rgba(244,63,94,0.15)", border: "1px solid rgba(244,63,94,0.3)", boxShadow: "0 0 20px rgba(244,63,94,0.1)" }}>
            <TrendingDown size={22} style={{ color: "#f43f5e" }} />
          </div>
          <div>
            <h2 className="text-xl font-bold tracking-tight" style={{ color: "var(--text)" }}>
              Welcome to DeepPuts
            </h2>
            <p className="text-sm mt-1 font-medium" style={{ color: "var(--text-3)" }}>
              AI-powered bearish market intelligence
            </p>
          </div>
        </div>

        {/* Scrollable EULA Snippet */}
        <div className="rounded-xl p-4 overflow-y-auto max-h-40 space-y-3"
          style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.1)" }}>
          <div className="flex items-center gap-2 mb-2">
            <AlertTriangle size={14} style={{ color: "#f59e0b", flexShrink: 0 }} />
            <span className="text-xs font-bold uppercase tracking-wider" style={{ color: "#f59e0b" }}>
              Critical Risk Disclosure
            </span>
          </div>
          <div className="space-y-3 text-xs leading-relaxed" style={{ color: "var(--text-2)" }}>
            <p>
              <strong style={{ color: "var(--text)" }}>1. Not Financial Advice:</strong> DeepPuts is a research tool, not a registered investment advisor. All bear theses, conviction scores, and signal classifications are automatically generated by AI models. They may be inaccurate, incomplete, or entirely hallucinated.
            </p>
            <p>
              <strong style={{ color: "var(--text)" }}>2. Infinite Risk Warning:</strong> Short selling and put options trading carry significant risk of unlimited losses. You can lose substantially more than your initial investment if the market moves against you.
            </p>
            <p>
              <strong style={{ color: "var(--text)" }}>3. No Guarantees:</strong> Past performance of flagged signals is absolutely not indicative of future results. Never make an investment decision solely based on DeepPuts. Always conduct independent due diligence.
            </p>
          </div>
        </div>

        {/* 3 Checkboxes */}
        <div className="space-y-3 pt-2">
          {[
            "I understand DeepPuts provides AI-generated analysis for research purposes only, not financial advice.",
            "I acknowledge the significant, potentially unlimited risks involved with short selling and options trading.",
            <>I accept the <a href="/tos" target="_blank" rel="noopener noreferrer" style={{ color: "#f43f5e" }} onClick={e => e.stopPropagation()}>Terms of Service</a> and <a href="/privacy" target="_blank" rel="noopener noreferrer" style={{ color: "#f43f5e" }} onClick={e => e.stopPropagation()}>Privacy Policy</a>.</>
          ].map((label, idx) => (
            <label key={idx} className="flex items-start gap-3 cursor-pointer group p-2 -mx-2 rounded-lg transition-colors"
              style={{ background: checks[idx] ? "rgba(244,63,94,0.05)" : "transparent" }}
              onMouseEnter={e => { if (!checks[idx]) e.currentTarget.style.background = "rgba(255,255,255,0.03)"; }}
              onMouseLeave={e => { if (!checks[idx]) e.currentTarget.style.background = "transparent"; }}
            >
              <div className="relative flex items-center justify-center mt-0.5 shrink-0 w-4 h-4 rounded border transition-all"
                style={{
                  borderColor: checks[idx] ? "#f43f5e" : "var(--border)",
                  background: checks[idx] ? "#f43f5e" : "transparent"
                }}>
                <input
                  type="checkbox"
                  checked={checks[idx]}
                  onChange={e => {
                    const newChecks = [...checks];
                    newChecks[idx] = e.target.checked;
                    setChecks(newChecks);
                  }}
                  className="absolute opacity-0 w-full h-full cursor-pointer"
                />
                {checks[idx] && <CheckCircle size={12} style={{ color: "#fff" }} />}
              </div>
              <span className="text-xs leading-relaxed font-medium transition-colors" style={{ color: checks[idx] ? "var(--text)" : "var(--text-3)" }}>
                {label}
              </span>
            </label>
          ))}
        </div>

        <button
          onClick={accept}
          disabled={!allChecked || accepting}
          className="w-full py-3 text-sm font-bold rounded-xl transition-all shadow-lg"
          style={{
            background: !allChecked || accepting ? "rgba(244,63,94,0.2)" : "linear-gradient(135deg, #f43f5e, #fb7185)",
            color: !allChecked || accepting ? "rgba(255,255,255,0.4)" : "#fff",
            cursor: !allChecked || accepting ? "not-allowed" : "pointer",
            border: `1px solid ${!allChecked || accepting ? "transparent" : "rgba(255,255,255,0.2)"}`
          }}
          onMouseEnter={e => { if (allChecked && !accepting) e.currentTarget.style.filter = "brightness(1.1)"; }}
          onMouseLeave={e => { if (allChecked && !accepting) e.currentTarget.style.filter = "brightness(1)"; }}
        >
          {accepting ? "Saving…" : "I Understand — Enter DeepPuts"}
        </button>
      </div>
    </div>
  );
}
